version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: tododb
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: jxien/todo-backend:latest
    container_name: todo-backend
    restart: always
    environment:
      DATABASE_URL: mysql://todo_user:user123@mysql:3306/tododb
    depends_on:
      - mysql
    ports:
      - "3001:3001"

volumes:
  mysql_data:
