apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # Ou LoadBalancer si cloud
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
