apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: cm9vdHB3ZA==     # "rootpwd"
  password: dXNlcjEyMw==          # "user123"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  database_url: bXlzcWw6Ly90b2RvX3VzZXI6dXNlcjEyM0BteXNxbDozMzA2L3RvZG9kYg==   # "mysql://todo_user:user123@mysql:3306/tododb"